[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  command = "echo Building Functions"
[[redirects]]
  from = "/*"
  to = "/:splat"
  [redirects.rate_limit] # Protecting the entire app.
      window_limit = 2 # 2  = Request Amount
      window_size = 10 # 10 = Seconds
      aggregate_by = ["domain", "ip"]