[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  command = "echo Building Functions"
[[redirects]]
  from = "/*"
  to = "/:splat"
  [redirects.rate_limit] # Protecting the entire app.
      window_limit = 50
      window_size = 60
      aggregate_by = ["domain", "ip"]